CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
	CREATE TYPE pricing_model AS ENUM ('free', 'paid', 'freemium', 'subscription');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
	CREATE TYPE release_type AS ENUM ('immediate', 'manual', 'scheduled');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
	CREATE TYPE age_rating AS ENUM ('4+', '9+', '12+', '17+');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
	CREATE TYPE app_status AS ENUM ('draft', 'pending_review', 'approved', 'rejected');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	password_salt TEXT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
	id INTEGER REFERENCES users(id) ON DELETE CASCADE PRIMARY KEY,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW(),
	developer_status VARCHAR(20) DEFAULT 'not_applied',
	first_name TEXT,
	last_name TEXT,
	avatar_url TEXT
);

CREATE TABLE IF NOT EXISTS apps (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
	name VARCHAR(100) NOT NULL,
	subtitle VARCHAR(100),
	description TEXT NOT NULL,
	primary_category VARCHAR(50) NOT NULL,
	subcategory VARCHAR(50),
	keywords TEXT[] NOT NULL DEFAULT '{}',
	support_url TEXT NOT NULL,
	privacy_policy_url TEXT NOT NULL,
	contact_email TEXT NOT NULL,
	app_url TEXT NOT NULL DEFAULT '',
	icon_url TEXT NOT NULL DEFAULT '',
	pricing_model pricing_model NOT NULL,
	price DECIMAL(10, 2),
	currency VARCHAR(3),
	release_type release_type NOT NULL,
	scheduled_release_date TIMESTAMPTZ,
	is_preorder BOOLEAN DEFAULT false,
	age_rating age_rating NOT NULL,
	content_descriptors TEXT[],
	review_notes TEXT,
	status app_status DEFAULT 'draft',
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW(),
	slug TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS app_assets (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_id INTEGER REFERENCES apps(id) ON DELETE CASCADE NOT NULL,
	asset_type VARCHAR(20) NOT NULL,
	file_path TEXT NOT NULL,
	file_size INTEGER NOT NULL,
	width INTEGER,
	height INTEGER,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_territories (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_id INTEGER REFERENCES apps(id) ON DELETE CASCADE NOT NULL,
	territory_code VARCHAR(2) NOT NULL,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE(app_id, territory_code)
);

CREATE TABLE IF NOT EXISTS app_reviews (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_id INTEGER REFERENCES apps(id) ON DELETE CASCADE NOT NULL,
	reviewer_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
	status app_status NOT NULL,
	feedback TEXT,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_apps_updated_at ON apps;
CREATE TRIGGER update_apps_updated_at
BEFORE UPDATE ON apps
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_app_reviews_updated_at ON app_reviews;
CREATE TRIGGER update_app_reviews_updated_at
BEFORE UPDATE ON app_reviews
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
